#!/usr/bin/env bash
#MISE description="check tools"

set -e

# Colors
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
BLUE='\033[34m'
MAGENTA='\033[35m'
BOLD='\033[1m'
RESET='\033[0m'

check_expected_version() {
  expected_version=$(grep "$1" .tool-versions | cut -d " " -f 2)
  if [[ "$2" != *"$expected_version"* ]]
  then
    echo -e "${RED} expected your environment to have ${1}" \
            "${expected_version} but found ${2} ${RESET}"
    echo -e "${RED} ... try running 'mise install'${RESET}"
    exit 1
  else
    echo -e "✅ found expected version of ${BOLD}${1}${RESET}" \
            "${GREEN}${expected_version}${RESET}"
  fi
}

check_expected_version nodejs "$(node -v)"

echo -e "${GREEN}"all your tools look fine 🎉 "${NC}"
