[tasks.install]
description = "install all dependencies"
run = "echo TODO: install goes here"

[tasks.check]
description = "check all dependencies"
depends = ["install", "check-tools"]
run = "echo TODO: check goes here"

[tasks.lint]
description = "lint"
run = "npm run lint"

[tasks."build:next"]
description = "build next app"
run = "npm run build"

[tasks.build]
description = "build all the things"
depends = ["check", "lint", "build:next"]
run = "echo lint and build"

[tasks.clean]
description = "clean up"
run = "echo TODO: clean goes here"

[tools]
node = "latest"
