[tasks.install]
description = "install all dependencies"
run = "npm install"

[tasks.check]
description = "check all dependencies"
depends = ["install", "check-tools"]
run = "echo TODO: check goes here"

[tasks.lint]
description = "lint"
depends = ["install"]
run = "npm run lint"

[tasks."build:next"]
description = "build next app"
depends = ["install"]
run = "npm run build"

[tasks.build]
description = "build all the things"
depends = ["check", "lint", "build:next"]
run = "echo lint and build"

[tasks.clean]
description = "clean up"
run = [
  "echo cleaning 🧹",
  "rm -rf .node",
  "rm -rf node_modules",
]

[tools]
node = "latest"
